### ISSUE TITLE
Errormessage: "Unknown card file type" when importing file from win10

### ISSUE THREAD

**Issue by lhpitn** [antboy/CardFileKPPlugin#1]
Hi,
i tried to import the file just before exported from windows login data storage and just got this error
````
---------------------------
Warning
---------------------------
Unknown card file type: 
---------------------------
OK   
---------------------------
````

![grafik](https://user-images.githubusercontent.com/45788285/67751967-63bab500-fa32-11e9-9068-666429e909db.png)

thanks in advance

**Comment by antboy** [comment]
Hi lhpitn,

this Keepass plugin is not intended to do that and does not have that functionality.

The message means that the file you were trying to import was not a valid "Microsoft Cardfile".
Cardfile is described here:  https://en.wikipedia.org/wiki/Cardfile

The original cardfile program is available from here:
http://www.northshorepc.com/download/cardfile32bit/32_bit_cardfile.exe

**Comment by lem0n4id** [comment]
i have the same issue, i exported from windows Credential Manager and when i try to import in keepass, i get this error.
Any solution for this problem?

**Comment by antboy** [comment]
Hi lem0n4id,

this Keepass plugin is not intended to do that and does not have that functionality.  Please see the earlier [reply](https://github.com/antboy/CardFileKPPlugin/issues/1#issuecomment-547425373).

I can only suggest you have a look [here](https://keepass.info/plugins.html) to see if there are other Keepass plugins that can do what you want.

Good luck.

**Comment by lem0n4id** [comment]
ok thank you
